import type { Metadata } from "next";
import { Inter, Outfit} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Headers from "./_components/Headers";

const inter = Outfit({
  //variable: "--font-geist-sans",
  subsets: ["latin"],
});

/* const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" data-theme="light">
       <body className={inter.className}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
